### ISSUE TITLE
v4 does not work with Angular 12

### ISSUE THREAD

**Issue by madmacc** [gavinmcfarland/flex-gap-polyfill#93]
I have tried 4.1.0 and 4.2.0 with Angular 12.
Both of these cause ng build to freeze at "Generating browser application bundles (phase: building)...
If I move back to 2.2.1 the build works.

I am trying to upgrade as it does not seem to be working with row-gap.

**Comment by gavinmcfarland** [comment]
Would you mind providing a repo and I can take a look at what's causing it to freeze? Thank you

**Comment by gavinmcfarland** [comment]
If you can create a repo with Angular 12 I can maybe investigate and try and see what's causing the issue. But otherwise I think I'll have to close this issue because it seems that Angular doesn't support PostCSS anymore for a few versions. Apologies for any inconvenience.

I found the following articles talking about enabling PostCSS support for Angular and it seems like they've ditched it for now. It's not been supported for a few versions now. Somebody talks about getting it to work with a custom build. It may be useful for someone that's interested in trying it.

Various links I found below about it below:

https://github.com/angular/angular-cli/issues/26536
https://github.com/nrwl/nx/issues/9650
https://medium.com/@kabya78890/install-tailwind-css-using-post-css-in-your-angular-project-9cc0f9a3927b

I'll be closing this issue for now.
